version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./server/config:/app/server/config:ro
      - ./server/assets:/app/server/assets:ro
    environment:
      - NODE_ENV=production
      - PORT=5000
