version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./server/config:/app/config:ro
      - ./server/assets:/app/assets:ro
    environment:
      - NODE_ENV=production
