version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5000}
    volumes:
      - ./server/config:/app/config:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT:-5000}/api/locations"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
