[project]
name = "photonglass"
version = "0.1.0"
description = "A network monitoring and diagnostic tool with Hyperglass-inspired UI"
requires-python = ">=3.11"
dependencies = [
    "netmiko>=4.5.0",
    "pyyaml>=6.0.2",
]
