devices:
  "router1.chi":
    host: "10.0.1.1"
    username: "admin"
    password: "secure123"
    device_type: "cisco_ios"
    description: "Chicago Core Router"
    enabled_commands: ["ping", "traceroute"]
    location_id: "chi"
  "router2.nyc":
    host: "10.0.2.1"
    username: "admin"
    password: "secure123"
    device_type: "cisco_ios"
    description: "New York Core Router"
    enabled_commands: ["ping", "traceroute"]
    location_id: "nyc"
