import { DeviceConfig } from "@/lib/types";

export const LOCATIONS = [
  {
    id: "chi",
    deviceName: "Chicago Core Router 1",
    subtext: "Chicago, IL",
    deviceHost: "router1.chi"
  },
  {
    id: "nyc",
    deviceName: "New York Core Router 1",
    subtext: "New York, NY",
    deviceHost: "router2.nyc"
  }
];

// Device configurations are loaded from YAML through config_loader.py
// Import the configurations generated by config_loader.py
import { DEVICES } from './config/devices';
