import { DeviceConfig } from "@/lib/types";

export const LOCATIONS = [
  {
    id: "chi",
    city: "Chicago, IL",
    code: "US-CHI",
    shortCode: "CI",
    deviceHost: "router1.chi"
  },
  {
    id: "nyc",
    city: "New York, NY",
    code: "US-NYC", 
    shortCode: "NN",
    deviceHost: "router2.nyc"
  }
];

// Device configurations are loaded from YAML through config_loader.py
// Import the configurations generated by config_loader.py
import { DEVICES } from './config/devices';
