# Network Diagnostic Commands Configuration
# Each command entry must have:
# - type: Unique identifier for the command
# - label: Display name in the UI
# - template: Command template with {target} placeholder
# - description: (optional) Detailed description
# - subType: (optional) Specific command subtype (path/community/route)
# - inputPlaceholder: Helper text for input field

commands:
  ping:
    type: ping
    label: Ping1
    template: "ping {target}"
    description: "Send ICMP echo requests to a target"
    inputPlaceholder: "Enter IP or hostname"

  traceroute:
    type: traceroute
    label: Traceroute
    template: "traceroute {target}"
    description: "Print the route packets take to a target"
    inputPlaceholder: "Enter IP or hostname"

  mtr:
    type: mtr
    label: MTR
    template: "mtr {target}"
    description: "Continuously traceroute to a target"
    inputPlaceholder: "Enter IP or hostname"

  bgp_path:
    type: bgp_path
    label: BGP AS Path
    template: "show ip bgp paths {target}"
    description: "Show BGP AS path information"
    subType: path
    inputPlaceholder: "Enter IP prefix or ASN"

  bgp_community:
    type: bgp_community
    label: BGP Community
    template: "show ip bgp community {target}"
    description: "Show BGP community information"
    subType: community
    inputPlaceholder: "Enter community value"

  bgp_route:
    type: bgp_route
    label: BGP Route
    template: "show ip bgp {target}"
    description: "Show BGP route information"
    subType: route
    inputPlaceholder: "Enter IP prefix"
