branding:
  logo:
    light: "/assets/logo-light.svg"
    dark: "/assets/logo-dark.svg"
  header:
    title: "Photonglass"
    subtitle: "Network Monitoring and Diagnostic Tool"
  footer:
    text: "© 2024 Photonglass"
    links:
      - label: "Documentation"
        url: "/docs"
      - label: "Support"
        url: "/support"
    contact:
      email: "support@example.com"
      phone: "+1 (555) 123-4567"
